sys:
    preiod: 1000


spring:
    datasource:
        url: jdbc:mysql://localhost:3306/agriculture?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: root
        password: hanjinhao
        driver-class-name: com.mysql.cj.jdbc.Driver
        platform: mysql

    jpa:
        database: mysql
        show-sql: false
        properties: 
            hibernate: 
                hbm2ddl:
                    auto: update
                jdbc: 
                    batch_size: 500
                    batch_versioned_data: true
