#pragma once
#define NOMINMAX
#include <winsock2.h>
#include <windows.h>
#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include <iostream>
#include <iterator>
#include <locale>
#include <numeric>
#include <print>
#include <string>
#include <vector>
#include <ranges>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <unordered_map>
#include <unordered_set>
#include <thread>
#pragma comment(lib,"Ws2_32.lib")